### ISSUE TITLE
Issue with image file compression

### ISSUE THREAD

**Issue by AragoniteDragon** [FanTranslatorsInternational/Kuriimu2#101] opened 2021-04-30 00:32 UTC
**Game Name**: Fire Emblem (IF) Fates
**Console**: 3DS
**Format extension(s)**: .bch, .bch.lz
**Type**: Image

Kuriimu 2 fails to compress any bch file with any compression type , and .png files only produce filename.png.out instead of compressing correctly. Trying to compress bch files using LZ77 and Reverse LZ77.

More details:
Kuriimu 1 also fails when attempting to use Reverse LZ77 compression.

Sample files (if possible): screenshot of error messages (Kuriimu 2 won't save any logs), and attached bch file
![image](https://user-images.githubusercontent.com/32208872/116634233-8086c000-a929-11eb-8786-b3f94aded791.png)
![image](https://user-images.githubusercontent.com/32208872/116634290-9f855200-a929-11eb-9cfb-9c93d7c44d68.png)

[https://www.mediafire.com/file/ld31efcinlknaf4/%25E9%2580%259A%25E5%25B8%25B8.bch/file](url)

**Comment by onepiecefreak3** [comment] 2021-04-30 06:55
The Backwards LZ77 of Kuriimu1 is flawed as it requires a file to exist, which cannot exist.
It's an artifact from debugging, and will not be fixed, since Kuriimu1 is deprecated.

As for Kuriimu2, the issue cannot be reproduced. The BCH can be compressed successfully without a problem and is valid. It can also be decompressed successfully. Make sure that the file you want to de-/compress is not open somewhere else, since that can lead to the not processed successfully error. We try to make the log more detailed about this in future releases.

Close this issue, if what I said helped you to solve the problem.

**Comment by onepiecefreak3** [comment] 2021-04-30 09:03
Starting with the newest dev build and later on Release 1.2.1 those logging messages will be more expressive, both in style and information.

**Comment by AragoniteDragon** [comment] 2021-04-30 22:32
After attempting again with nothing else open on the computer, the operation succeeded but the file produces was labeled as "通常.bch.out" instead of "通常.bch.lz" like intended and after the execution the log is still completely empty.

**Comment by onepiecefreak3** [comment] 2021-05-01 07:39
The tool doesn't know what extension is "intended". It just uses some name change (adding ".out") to differentiate the input from the output file. If you want an ".lz" extension, just rename the file to ".lz". Changing the file name/extension, doesn't change its content after all. No, this behaviour is configurable.

The log of those operations is written clearly in the black box on the dialog, you have open. Writing those information exactly like this into another log, which persist on the drive, is not just redundant, but imo a waste of memory.

Since those two points are non-issues, I will close this issue again.

**Closed by onepiecefreak3** 2021-05-01 07:39 UTC
Labels: Compression, bug, good first issue
