### ISSUE TITLE
Error at start

### ISSUE THREAD

**Issue by antoineok** [FanTranslatorsInternational/Kuriimu2#90] opened 2021-04-11 14:47 UTC
Bug details:  
I can't start kuriimu, right after the start command is executed, i have an error.

the error:
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at Kuriimu2.EtoForms.Gtk.MainClass.Main(String[] args)µ
   
  Os: Manjaro xfce 64bits latest version
  Dotnet version: 3.1.113 (the last according to pacman)

**Comment by onepiecefreak3** [comment] 2021-04-11 18:06
The issue is related to this problem on EtoForms.Gtk: https://github.com/picoe/Eto/issues/1914
Until this issue is solved and integrated in the next EtoForms release, this issue can be closed.

**Comment by onepiecefreak3** [comment] 2021-04-22 16:17
This is fixed in the newest dev build and will be included in Release 1.2.1.

**Closed by onepiecefreak3** 2021-04-22 16:17 UTC
