### ISSUE TITLE
MTArc and TEX format problems

### ISSUE THREAD

**Issue by MikominMM** [FanTranslatorsInternational/Kuriimu2#73] opened 2021-03-18 12:33 UTC
Game Name: Sengoku Basara 3\Sengoku Basara 4 (MT Framework)
Console: PS3/PS4
Format extension(s): ARC, TEX  
Type: [ image | archive]  

Bug details:  
First ARC file has this error: Unable to read beyond the end of the stream.
Second ARC file has this error: Specified argument was out of the range of valid values. (Parameter 'offset)
Third TEX file has this error: MTex version 0x9D is not supported 
Fourth ARC file has this error: File is marked as compressed but doesn't use ZLib
Fifth TEX file has this error: MTex version 0x97 is not supported (from Basara 3 PS3)

Sample files (if possible):  
https://mega.nz/file/JPQSDZgL#i_SEskUKp6PZ3DfcqsH8x5Y-txRmIPpo0DrPmNv3tmw
https://mega.nz/file/ZbJWHBBC#prsRy3fNn3cjBzCp4dLjax7fWF7Pf1xvOiJjLrtbexU
https://mega.nz/file/8eAGwJSS#tEEeLVM-uDxXRq2rTTqot4eQi15eDq6UOT39Q2EPifk
https://mega.nz/file/kOB0TD7Q#1YITc5Mo4mnIYtdVHKzgD4N6Fh0RDwDFfe9jBUVEqpY
https://mega.nz/file/ESICHTgB#QtuQj03MBvElzDMh_wG_Ts-OF7n0GLrVERYJcRrajrE

**Comment by onepiecefreak3** [comment] 2021-03-18 18:00
Issue 1 cannot be resolved, since the TEX relies on a Nintendo format BRES, which is not yet part of Kuriimu2.
Issue 2 cannot be reproduced for Kuriimu2, since it does not have support for HFS archives.
Issue 3 the same as Issue 2.
Issue 4 was resolved by adding 0x9D as a known format for PS3.
Issue 5 the same as Issue 2.
Issue 6 was resolved by adding 0x97 as a known version for PS3.

**Comment by onepiecefreak3** [comment] 2021-03-20 08:55
Issue 1, 2, and 4 are solved for loading: HFS contains a footer to check its contents for unauthorized changes. Since we don't know the checksum used, saving is disabled for HFS.

**Comment by onepiecefreak3** [comment] 2021-03-20 09:57
All bugs are resolved, beside "horse000.arc" which seems to be messed with. However, it was stated that this is not the case. Please make an extra issue for that. Giving more details to the game, file itself, and so on.

**Closed by onepiecefreak3** 2021-03-20 09:57 UTC
Labels: good first issue
